### ISSUE TITLE
Adjust ESM Release file to match default unattended-upgrades behavior

### ISSUE THREAD

**Issue by vorlonofportland** [CanonicalLtd/archive-auth-mirror#43]
unattended-upgrades by default matches on the release and security pockets of only the official Ubuntu release.  This relies on the following fields in the archive Release file for a correct match:

Origin: Ubuntu
Suite: precise-security

According to STS, these are not present in the Release file for the ESM archive.  Please add them.

**Comment by vorlonofportland** [comment]
Discussed with Adam Conrad that we don't want to misrepresent the esm archive as being an archive it isn't.  We need Origin and Suite set but should not collide with the main archive.  Instead we will SRU unattended-upgrades to additionally recognize the ESM archive and enable it by default.

So the values we want are:
  Origin: UbuntuESM
  Suite: precise

(Suite: precise-security might be more conceptually correct, but we are concerned that presenting a value that doesn't match the archive file path could cause  tool confusion.)

**Comment by panlinux** [comment]
I deployed this charm and these are the results (10.55.60.98 is my test deployment server):
```
# apt-cache policy
(...)
 500 https://10.55.60.98/ubuntu/ precise/main i386 Packages
     release o=UbuntuESM,a=precise,n=precise,l=precise archive,c=main
     origin 10.55.60.98
 500 https://10.55.60.98/ubuntu/ precise/main amd64 Packages
     release o=UbuntuESM,a=precise,n=precise,l=precise archive,c=main
     origin 10.55.60.98

root@precise-esm:~# head -n 7 /var/lib/apt/lists/10.55.60.98_ubuntu_dists_precise_Release
Origin: UbuntuESM
Label: precise archive
Suite: precise
Codename: precise
Date: Mon, 01 May 2017 15:34:41 UTC
Architectures: i386 amd64
Components: main
```
The "`l`" flag is different in a normal precise archive, not sure if that's relevant. It says "`Ubuntu`" instead of "`precise archive`" as in the ESM case:
```
 500 http://br.archive.ubuntu.com/ubuntu/ precise/main amd64 Packages
     release v=12.04,o=Ubuntu,a=precise,n=precise,l=Ubuntu,c=main
     origin br.archive.ubuntu.com
```

**Comment by albertodonato** [comment]
@panlinux I changed the template to use the Origin value as Label too. AFAIU the label is just a description, but it makes more sense for it to match the origin than the suite.
