### ISSUE TITLE
nginx's auth_backend not updated correctly: only keeps ip of last unit

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/archive-auth-mirror#49]
I deployed `archive-auth-mirror` and related it to `basic-auth-service`. I didn't check `/etc/nginx/sites-enabled/archive-auth-mirror`'s `auth_backend` at that point so I can't say what it looked like.

I then added another `basic-auth-service` unit, and then I checked `/etc/nginx/sites-enabled/archive-auth-mirror` and it was pointing at just the new unit, instead of both:
```
upstream auth_backend {
    server 10.0.100.51:8080;
}
```
I then destroyed the new unit (ran into [basic-auth-service issue #1](https://github.com/CanonicalLtd/basic-auth-service-charm/issues/1)) and after cleaning up the error the `auth_backend` section was still not modified. Maybe related to the bug, so let's not fret yet.

So I added another unit, which gave me `basic-auth-service/2`. Now the `auth_backend` section reads like this:
```
upstream auth_backend {
    server 10.0.100.18:8080;
}
```
That is the IP of the new unit. Looks like it's only considering the last unit. I was expecting to see two IPs in there: one for each unit of `basic-auth-service`.

**Comment by albertodonato** [comment]
This is a bug in the basic-auth-check layer, see https://github.com/CanonicalLtd/juju-interface-basic-auth-check/issues/1
