### ISSUE TITLE
Repeated server entries in auth_backend

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/archive-auth-mirror#50]
Got this in our staging environment:
```
upstream auth_backend {
    server x.x.x.19:8080;
    server x.x.x.20:8080;
    server x.x.x.19:8080;
    server x.x.x.20:8080;
}
```
These addresses need to be a set or something, so that only unique ones are listed.

**Comment by albertodonato** [comment]
Fixed in https://github.com/CanonicalLtd/juju-interface-basic-auth-check/commit/e3c067a9e133db3efa11f0816378807bc13042c5
